### ISSUE TITLE
Merging back into Chrysalis

### ISSUE THREAD

**Issue by darix** [Dygmalab/Bazecor#106]
I wonder if you will merge back the changes into Chrysalis. It would have the advantage that packagers could package one tool and support more devices without maintaining the duplicated code.

For now I will work on a Bazecor package, because it is more important for my current device. 

(Typed from my raise that just arrived)

**Comment by AlexDygma** [comment]
Hello @darix !

In this case you should know we are planning to redo the whole project as the current one is based on outdated versions of Electron, React and Material.UI which have no clear pathways to upgrade due to the quantity of required changes to upgrade them from the current versions to the up to date ones.

this is a blocking issue and will make us abandon the current codebase and redo the whole interface using bootstrap and a newer WebPack version that does not cross the dependencies and uses modern code patterns to access the system's utilities from electron.

this will obviously make the codebase not compatible with Chrysalis any more, but it's the only path we have forward, that is the reason why it's not in our plans to further support this version when we arrive to 0.3.

all the enhancements listed here will be implemented in the newer version in a new repository.

**Comment by darix** [comment]
yeah your electron version is stuck on a really old version too. looking forward to see what is coming next
