### ISSUE TITLE
UI Crashing on Load (Catalina 10.15.7)

### ISSUE THREAD

**Issue by sos0** [Dygmalab/Bazecor#127]
**Describe the bug**
Bazecor UI crashing on load (happens intermittently)
<img width="1565" alt="image" src="https://user-images.githubusercontent.com/1973082/99224628-87ff4600-279b-11eb-8bf3-459d12dcd5be.png">

Zooming in on the error:
<img width="426" alt="image" src="https://user-images.githubusercontent.com/1973082/99224882-f9d78f80-279b-11eb-85e7-9f2a5818752d.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Bazecor Version: 0.2.4.132

**Additional context**
- Attempting to firmware reset cleared the keyboard layout and I can no longer import the old layer from 0.2.2 but this is likely another bug.

**Comment by AlexDygma** [comment]
Hello @sos0 !

I'm sorry you are getting this error, its a pain to have the app close itself when you are working with it.

as you can see in the console, we already located where and when this error happens, because it's documented as "there is no spoon error".

The reason it happens is that the current state of the react component gets lost due to the focus API losing connection / any other reason that can trigger the serial interface to be unable to respond. 

I did try to fix this by adding a state restoring function that solves the bug, but this happens in render time, so i cannot stop the render flow to update the state as this will make the component enter a loop and it's forbidden by react.

As this is happening too often ill try to dig more into it.

I'll share the progress here 💪.

**Comment by AlexDygma** [comment]
This has been resolved by pushing ahead Electron version and addressing the code that lacked state to represent the content by going back to keyboard select screen when it happens.
