### ISSUE TITLE
Unknown publisher

### ISSUE THREAD

**Issue by MScudeller** [Dygmalab/Bazecor#129]
**Describe the bug**
When running Bazecor installer, my Windows complain that it comes from an unknown publisher and that I should not run the exe

**To Reproduce**
1. Run the installer for the first time

**Expected behavior**
Windows should not ask the user as if it is a threat to windows

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Bazecor Version: 0.2.4

**Comment by AlexDygma** [comment]
Hello @MScudeller !

You are totally right, this happens because we are using Travis as our continuous integration process and the applications compiled by it are not signed by default.

We are working in the steps to get Bazecor signed, but it will take us some time, so bear with us for a little here 😥. 

I'll try to push this to 0.2.5.
