### ISSUE TITLE
Dygma Raise restarts when trying to connect with Bazecor 0.3.1

### ISSUE THREAD

**Issue by Oddj0b** [Dygmalab/Bazecor#198]
**Describe the bug**
After downloading the Bazecor 0.3.1 I can't connect to the Dygma Raise, when trying the LEDs turn off for half a second and then back on. The Bazecor software says that the connection breaks.

**To Reproduce**
1. Open Bazecor 0.3.1
2. Click **Connect**
3. In the lower left Bazecor shows a **Keyboard disconnected** warning and a **Communication timeout** message.

**Expected behavior**
I would expect to enter the layout editor.

**Screenshots**
![bazecor communication error](https://user-images.githubusercontent.com/1084916/114279004-b32c4f80-9a32-11eb-8c57-75f3db0d45d4.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 (version 20H2 | OS build 19042.867)
 - Bazecor Version: 0.3.1

**Additional context**

**Comment by Oddj0b** [comment]
As a piece of bonus information the keyboard is directly connected to the machine, and I haven't been able to upgrade the firmware as the error happens while connecting to the keyboard.

**Comment by GazHank** [comment]
Hi @Oddj0b,  would you be able to share a screenshot of the developer console?  you should be able to activate this by either pressing Ctrl+Shift+i or using the setting found in the preferences under advanced.

It should look something like:
![image](https://user-images.githubusercontent.com/64541249/114302438-ecab9c00-9ac0-11eb-9d58-1edc47946c7e.png)

I think we will need to add some more logging as the debug console isn't perfect for situations like this, but it might give some more info to investigate the problem.

ps - have you tried using different ports on your PC, I've just seen some reports (on Reddit) of someone facing issues when using a slow USB port (I wonder if a recent change has impacted connectivity for older slower ports)

**Comment by Oddj0b** [comment]
![bazecor communication error w console](https://user-images.githubusercontent.com/1084916/114418896-3d9bbd00-9bb3-11eb-8823-73bd56fe4416.PNG)

Here you go, I haven't tried other ports. But given that the port is returning support = `true` and then `false` it might be a solution.

**Comment by Oddj0b** [comment]
OK, switching the port made it work and I just flashed my firmware up to version `0.3.1` from `0.2.7`.

**Comment by Oddj0b** [comment]
The problem persists after flashing and switching back to the original port.

**Comment by GazHank** [comment]
Thanks @Oddj0b, while perhaps not ideal it sounds like you have a bit of a workaround while we get to the bottom of the issue.  Do you know if there is any difference between the 2 ports (USB 2 vs USB 3 etc)?

It's very strange to me, as there is no deliberate change to the components of the software that deal with connectivity between version 0.2.7 and 0.3.1.  Yet other people have reported similar issues of not being able to use older/slower USB ports that previously worked.

I'm going to see about adding some more logging of the USB connectivity processes, so that we see if a root cause can be found.

@AlexDygma I was considering pulling https://github.com/keyboardio/Chrysalis/commit/3d06fc5724b89e957fc2b5fcc3f0fcfcbf4b2b70 from Chrysalis in the first instance to see if that helps debug this kind of issue, but at the moment it looks like they don't log any more info than we send to the dev console.  Let me know if you have any thoughts or preferences for how any additional error logging is handled

**Comment by AlexDygma** [comment]
Hey @Oddj0b !

if you have a problem related to a certain USB port, I'm inclined to think the issue is related either to physical connectivity or maximum load of that port, the raise can consume quite a lot of current when all LED's are on, specially on white color, so i would try it out dimming the keyboard to 0% first to rule this out.

then, we should look to the USB telemetry, there are several applications for this available, here is even a Wireshark version that does this.

I normally use USBLyzer as it's pretty straightforward and easy to use. with the trial will be enough for this if you want to try it.

if we discard both of this things, we will need to do further digging by understanding where the software is making the keyboard hang, like @GazHank said!

let's hope that we discover the issue as fast as possible!.

**Comment by Oddj0b** [comment]
As a fun tidbit of information, I can't type my password on a Mac, but it works on my Windows machines.

But I'll check out both Wireshark and USBLyzer for data and post the updates in here.

**Comment by AlexDygma** [comment]
@Oddj0b This should be addressed on 0.3.2! try the new version and tell me if it still happens to you!

**Comment by Oddj0b** [comment]
@AlexDygma It no longer restarts the keyboard. I still get a timeout, though. If you find it helpful, I can run USBLyzer and USB telemetry, but from point of view this issue can be closed.

**Comment by AlexDygma** [comment]
great!
