### ISSUE TITLE
Polkit-Error on startup

### ISSUE THREAD

**Issue by scriptmode** [Dygmalab/Bazecor#199]
**Describe the bug**

![Bazecor-0 3 1-Error](https://user-images.githubusercontent.com/11327652/114382178-5c3a8d80-9b8c-11eb-9734-f959b48ef025.png)

**To Reproduce**
1. Start Bazecor v0.3.1
2. See Error

**Desktop (please complete the following information):**
 - OS: Debian Testing, AwesomeWM
 - Bazecor Version: 0.3.1

**Additional context**
Not running a Desktop Environment like KDE or Gnome. Polkit seems to be a service for them.
App still starts and seems to work fine.

**Comment by AlexDygma** [comment]
Hey @scriptmode !

Bazecor for v0.3.1 requires a Polkit authentication agent to be present on the OS (which comes by default in virtually all major distributions).

this is because we now install Udev rules for you so that you can use the application without being root.

You should be fine after installing polkit-1-auth-agent, policykit-1-gnome, or polkit-kde-1. You can probably google other authentication agents for less known desktop environments.

Bazecor worked fine after it because the application doesn't require elevation, only the installation of the Udev rules, so you won't have problems using it.

**Comment by AlexDygma** [comment]
This was addressed by including a system dialog that first tells you what's going to happen (install Udev rules), then tries to do so, in case of error, it tells you:

```
{detail: "Your linux distribution lacks a polkit agent,  installing polkit-1-auth-agent, policykit-1-gnome, or polkit-kde-1 (depending on your desktop manager) will solve this problem"}
```
So the actual solution will be listed, if we wanted to push this further we could even install the dependencies automatically, but this will require some linux magic to know the dependencies depending your desktop window manager.

**Comment by marcofeltmann** [comment]
Hint for future me: You *must* start i.e. `lxqt-policy-agent` manually, if you're on CLI most of the time and use some lightweight compositor like `sway` over a full-featured window manager.  
Took me some minutes to figure out.

**Comment by devgioele** [comment]
Arch Linux users very often do only have a window manager and so might be interested in the following graphical authorization agent for polkit: [polkit-dumb-agent](https://aur.archlinux.org/packages/polkit-dumb-agent-git)

With `i3` or `sway` you can simple autostart it like:
```sh
exec "polkit-dumb-agent"
```
