### ISSUE TITLE
Post installation of firmware 0.3.3 issues regarding keyboard lighting and firmware upload

### ISSUE THREAD

**Issue by GAZelenka** [Dygmalab/Bazecor#209]
I have successfully upgraded the Raise firmware to 0.3.3 however after the firmware has been updated 2 problems have ocurred:
1. No layer colors, for any of the layers, are enabled. Changing LED mode using LED Next doesn't activate any of the lights on the keyboard either. The Neuron is lighting up as expected for any activated layers or LED modes.
2. I attempted to update the firmware again (to 0.3.3) however  received the  error message: 
"Error flashing the firmware The firmware update couldn't start because the Raise Bootloader wasn't found."
I have attempted the firmware update multiple times, holding the "Esc" key (top left) down as instructed, but have received the same error each time.

My Escape is normally configured to "Layer shift when held, normal key otherwise" which I have disabled in case the layer-shift was causing the problem, but this hasn't resolved the firmware update problem.

Desktop details:
 - Windows 10
 - Version 20H2 (OS Build 19042.928)
 - Bazecor Version: 0.3.3

**Comment by GazHank** [comment]
Hi @GAZelenka 

sorry to hear your facing issues, some of this sounds similar to problems I was debugging in of recent releases, so not sure if any of the following suggestions might work for you:

- LED Brightness - Since the LEDs aren't working (even in the lighting modes), you might want to check that the LED brightness setting found in preferences isn't set low.  _Changing the value and pushing that to the keyboard can also address some other preferences changes that were introduced in the last few releases, so worth updating the preferences anyway..._ 
- Colour Palette - In the Layout & Colourmap editor, are the colours in the palette set?  The colour palette is reloaded after a firmware update, and I've seen instances where all of the other settings are restored, but the colour is not (usually because something interfered with the update process).  The easiest fix for this is to restore/reload a backup of your layers, but if you don't have a backup then you might need to configure these from scratch.

On the second point of bootloader not found, it might be worth checking if a different USB port might work, it seems that some of the recent changes have increased the power consumption of the raise, which means people are finding issues when using the device on older / lower power USB ports (if you can it might be worth trying a USB 3/3.1 port if you have one on your machine)

If none of this helps then please let me know

Good luck

Gareth

**Comment by GAZelenka** [comment]
Hi Gareth,

Changing the LED Brightness and pushing the update fixed the issue with LED brightness. Changing the USB port has solved the firmware update issue. Thanks for your help.
