### ISSUE TITLE
Some strings/text in Bazecor are not listed in i18n/en.js

### ISSUE THREAD

**Issue by massimiliano-della-rovere** [Dygmalab/Bazecor#217]
I've localized the https://github.com/Dygmalab/Bazecor/blob/development/src/renderer/i18n/en.js i18n file into Italian, but I noticed that some string are still displayed in English: probably they are not indexed in en.js.

For example the following sections still appear in English:
* all the text in the popup windows (e.g. the firmware update process)
* the name of the keys and the categories

Please, can you update the en.js (and send me an email when it's done) so I can create a complete it.js fine and make a push request?

**Comment by AlexDygma** [comment]
Hi @massimiliano-della-rovere !

you're right! i will fix this as soon as possible so that you can finish and push your changes!

**Comment by massimiliano-della-rovere** [comment]
Let me know when the en.js file is updated so I can branch and do pull
request.

Il giorno mer 5 mag 2021 alle ore 10:03 AlexDygma ***@***.***>
ha scritto:

**Comment by javierguzman** [comment]
Hello! Right now, we have the internationalisation infrastructure but we only support English for two reasons:

1. It is harder to maintain software in multiple languages because every tiny change needs an update in all languages
2. Wording is something we pay attention to so we really need to understand the language to choose the best way to express what we want. 

So I close this issue though in future we would like to add at least a couple of very used languages when we have manpower to maintain that.
