### ISSUE TITLE
Some LED colors disappear / are not working as intended in dualboot configs (OS : Ubuntu/W10)

### ISSUE THREAD

**Issue by nyam-aste** [Dygmalab/Bazecor#224]
**Describe the bug**
Some colors (orange variants) do not carry over or disappear when using Bazecor on Windows 10 (by assigning a macro for example) and change OS on Ubuntu (maybe Ubuntu -> W10 but didn't notice it in this use case). This affects the color assigned to the last slot of the first column (so 9/10th color slot?) - I do not know if it affects others - and it does carry over the layouts / or has a weird effect on the other layouts (at least in Bazecor). The color can sometimes be shown on editor in Bazecor but is off on the actual keyboard.

To fix it, I have to reassign a color to it on the first (or others?) layout and it usually fixes it for all the layouts affected by it. But this has been happening for a while and I'm getting tired of doing it every time it happens.

**To Reproduce**
1. (Might be optional) Flash the firmware on Windows 10
2. Change macro/color/keybind on Windows 10
3. Boot to Linux/Ubuntu and see that the color is missing on the keyboard
4. Open Bazecor to realise that the color is shown on the editor on some layouts and/or became black on others.
**"Fix"**
5. Reassign the same or other color to the color slot to fix it. (Some times on one layout suffice, sometimes not.) 

**Expected behavior**
Not have the LED colors of the keyboard disappear / become blank when using Bazecor on both Windows 10 and Ubuntu / multiple OS. 

**Screenshots**
From Bazecor on Ubuntu : 
1st/ Default layout - we can see that the underglow is "orange" aswell as the "esc" key and their color slot has the color assigned but on the keyboard they are off / disabled : 
![image](https://user-images.githubusercontent.com/47141158/118967690-51350300-b96b-11eb-8c11-bdfb84f88772.png)
2nd/ Another layout that has the same "color" - if the fix is applied to the 1st layout, this one is fixed too - but this time the editor shows the color as disabled/blank :
![image](https://user-images.githubusercontent.com/47141158/118971058-40868c00-b96f-11eb-8496-8480b25652eb.png)

After the fix, the colors on the keyboard are fixed but in the editor, the other layouts stay the same (for example the 2nd - on the screenshot). So not "fixed" on the editor. 

Log from Bazecor :
-before applying "fix" :
[-1621508529034.log](https://github.com/Dygmalab/Bazecor/files/6515430/-1621508529034.log)
-after applying "fix" :
[-1621510264958-last.log](https://github.com/Dygmalab/Bazecor/files/6515502/-1621510264958-last.log)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 / Windows 10 N Education 
 - Bazecor Version: 0.3.3

**Additional context**
To fix it, I have to reassign a color to it on the first (or others?) layout and it usually fixes it for all the layouts affected by it. But this has been happening for a while and I'm getting tired of doing it every time it happens.

For v0.3.3, I had installed it on Windows 10 and flashed the firmware there; but I do use the v0.3.3 on Ubuntu as well. I do not recall for previous versions if I did too, but I usually flash the firmware on Ubuntu and I had this bug for a while now.

**Comment by GazHank** [comment]
@nyam-aste in trying to recreate your issue.  From my tests, it seems that the bottom left item in the color palette is behaving differently to the others, rather than the color Orange.   Would you be able to check if that matches your experience?

In particular all of the other pallete buttons as static / fixed for all layers; however the bottom left button displays differently for each layer selected.  

In practice, setting the bottom left hand palette button to a specific color, and applying this to the keyboard does work, and sets that color to all of the layers of the keyboard.  However the user interface still shows different colors for that button depending on the layer selected.

Steps to recreate issue:

1. select layer 0
2. change bottom left pallete button to red
3. save to keyboard (screenshot 1)
4. select layer 1
5. change bottom left pallete button to Green
6. save to keyboard (screenshot 2)
7. select layer 2
8. change bottom left pallete button to Blue
9. save to keyboard (screenshot 3)

After these steps each layer within the UI still matches the screen shots for the appropriate layer, however all keys assigned to the bottom left pallette button now show as blue per the last update (i.e. layer 2).  i.e. even though layer zero shows red in the UI the keyboard color for those keys is blue.

![image](https://user-images.githubusercontent.com/64541249/120048374-d628b800-c00e-11eb-8496-da030c9034ba.png)
![image](https://user-images.githubusercontent.com/64541249/120048458-0ff9be80-c00f-11eb-94f5-160b57add64f.png)
![image](https://user-images.githubusercontent.com/64541249/120048516-37508b80-c00f-11eb-8718-e829f828d635.png)


I'm not quite sure why this one pallete button is being treated as configurable per layer within the UI, but it does appear to be a Bazecor UI issue rather than an issue with the keyboard firmware.

I'll try to dig deeper, to see what is causing this, but wanted to double check that I'm understanding the issue correctly before diving into the code

cheers

Gaz

**Comment by GazHank** [comment]
Hi @AlexDygma, within Editor.js there are a couple of lines that set the pallete position 14 within the array.  

`palette[this.undeglowCount] = this.state.undeglowColors[this.state.currentLayer];`
and 
`newPalette[this.undeglowCount] = undeglowColors[event.target.value];`

Do you know what those bits of code are intended to do?  For some reason they seem to be making the bottom left pallete button (array item 14) behave as if it is layer specific, but I can't think of what they could be trying to do.  Commenting out those two sections seems to fix this issue, but the code is so deliberate, I can't help thinking that there is some broken functionality that those pieces were trying to achieve.

many thanks

Gaz

**Comment by nyam-aste** [comment]
> 
> 
> @nyam-aste in trying to recreate your issue. From my tests, it seems that the bottom left item in the color palette is behaving differently to the others, rather than the color Orange. Would you be able to check if that matches your experience?
> 
> In particular all of the other pallete buttons as static / fixed for all layers; however the bottom left button displays differently for each layer selected.
> 
> In practice, setting the bottom left hand palette button to a specific color, and applying this to the keyboard does work, and sets that color to all of the layers of the keyboard. However the user interface still shows different colors for that button depending on the layer selected.
> 
> Steps to recreate issue:
> 
>     1. select layer 0
> 
>     2. change bottom left pallete button to red
> 
>     3. save to keyboard (screenshot 1)
> 
>     4. select layer 1
> 
>     5. change bottom left pallete button to Green
> 
>     6. save to keyboard (screenshot 2)
> 
>     7. select layer 2
> 
>     8. change bottom left pallete button to Blue
> 
>     9. save to keyboard (screenshot 3)
> 
> 
> After these steps each layer within the UI still matches the screen shots for the appropriate layer, however all keys assigned to the bottom left pallette button now show as blue per the last update (i.e. layer 2). i.e. even though layer zero shows red in the UI the keyboard color for those keys is blue.
> 
> ![image](https://user-images.githubusercontent.com/64541249/120048374-d628b800-c00e-11eb-8496-da030c9034ba.png)
> ![image](https://user-images.githubusercontent.com/64541249/120048458-0ff9be80-c00f-11eb-94f5-160b57add64f.png)
> ![image](https://user-images.githubusercontent.com/64541249/120048516-37508b80-c00f-11eb-8718-e829f828d635.png)
> 
> I'm not quite sure why this one pallete button is being treated as configurable per layer within the UI, but it does appear to be a Bazecor UI issue rather than an issue with the keyboard firmware.
> 
> I'll try to dig deeper, to see what is causing this, but wanted to double check that I'm understanding the issue correctly before diving into the code
> 
> cheers
> 
> Gaz

Hi Gaz,

Yes I can confirm the behavior for that palette. When I change the black to orange (can be any other color) on layer 0, it stays black on the other layers. However, on the keyboard, the change is effective for the other layouts, even though on the UI, it's different.

Probably that the firmware has nothing to do with this, as I've already had the issue before. But tho, with 0.3.3 I couldn't flash it on linux but on windows. Anyway, I've always been inconsistent with flashing the firmware, sometimes I do it on windows, sometimes on linux. Just kinda lazy to change the boot.

My issue is that, if I make any changes on bazecor on windows (mostly just changing keybinding, macros on the gaming layer - I don't even touch the buggy palette), well it will be black/blank/empty on the keyboard the next time I boot into linux. I can only fix it by just changing or re-affecting the same color to the said palette on layer 0.

Thanks to you, I can now workaround it by not using that palette ! 👍 
(will keep updated if other palettes start getting affected)
