### ISSUE TITLE
allow more than 10 layers

### ISSUE THREAD

**Issue by yangkennyk** [Dygmalab/Bazecor#248]
**Is your feature request related to a problem? Please describe.**
I've created a sort vim emulation which ends up taking up a lot of layers, not leaving many left to use for other use cases

**Describe the solution you'd like**
being able to create more than 10 layers

**Describe alternatives you've considered**
creating a sort of frankenstein setup with karabiner

**Comment by GazHank** [comment]
it would be useful if you could share your layer setup, to understand the issue you are facing, and to see if there are alternative ways to achieve what you are trying to do

at the moment the limit of 10 layers is hardcorded into the firmware, and for the last 2 layers One Shot Layer dont even work https://github.com/Dygmalab/Bazecor/issues/221 (presumably because people very rarely using more than 8 layers).

As such, if there are usecases that really need the extra layers without extra workarounds then I'm sure it would be possible to re-engineer the firmware, but it would probably need a justificant for the extra dev investment

**Comment by briantoth** [comment]
I've been doing a similar thing (vim emulation) and run into the same issue.  The core problem is that a lot of vim "movements" and "commands" are based on two-key sequences.  For example you can delete a single word with "dw" or the remainder of the line with "d$".  For selecting text, "v$" selects everything to the end of the line, "vw" selects a word.  I also have a "search" layer which allows me to type text following "/" from normal mode.  I'm sure there are others that I don't use as frequently (for example, I dropped all of the commands that start with "g" to conserve layers).  This is all on top of the three "standard" layers for  vim's normal mode, normal mode + shift, and normal mode + control.

**Comment by javierguzman** [comment]
This is due to a memory limitation in the hardware so it is not possible :(
