### ISSUE TITLE
naming layers

### ISSUE THREAD

**Issue by yangkennyk** [Dygmalab/Bazecor#249]
**Is your feature request related to a problem? Please describe.**
just for usability it would be nice to be able to name layers so I don't have to remember what they are meant for by number

**Describe the solution you'd like**
allow renaming of layers opposed to just the numbers

**Describe alternatives you've considered**
none

**Comment by pabrams** [comment]
Yes this would be helpful, fun and easy

**Comment by GazHank** [comment]
Just a word of caution that any labels would not be saved to the firmware, so any users switching between multiple machines would find that the layer labels would not move with them.   We currently have this issue with the macros...

Since most users probably only use one machine, this seems reasonable, but it might be good to inform users in the UI so they aren't surprise that the label don't transfer to their new/alternative machine

**Comment by pabrams** [comment]
Yeah, I was wondering about that... 
What's the limitation, exactly? There's not any room for more data, at all? Or is it possible to update the firmware or somethign?

**Comment by GazHank** [comment]
It would be technically feasible, but it would use quite a bit of memory on the firmware.  

For each character permissible for each label it would use as much data as the mapping for a single key.  As such even if we kept the labels short, say 7 characters for 10 labels that would use the same space as mapping 70 keys or a layer.  I think more people would prefer an extra layer on their board, rather than layer labels that only show up in the app.

While not directly addressing this issue, there are a few other proposed changes which I think might help (they were placed on hold / back burner during the migration to the new version):
- Within the ui use a persistent list of layers; they could then show the layers using colour (perhaps the colour of the neutron for the given layer) - in that way the user can see the number and the colour of the layer when selecting.  This also encourages the use of the color as a layer identification aid both in the software and during normal use
- A HUD or semi-transparent pop up for the user when the layer is changed, perhaps depicting a visual of the layer and its number.  This would involve running bazecor in the background (/system tray), which would lead to other potential benefits such as being able to change layer when the in focus software changes.  Personally I think this might need a wee helper app, or for bazecor to go on a diet as since it uses electron (basically chrome) in the background, it's memory usage will be a bit high for lots of people to have running all of the time (especially gamers)

**Comment by pabrams** [comment]
I like your HUD idea.. but this was way too much for me right now (I had to learn a little react first, at least).

I have a PR up that is failing sig checks... I'll fix that later... Meanwhile, please comment on the PR.

**Comment by GazHank** [comment]
Nice work.  I won't have chance to build/ test for a few days as I'm travelling without a dev machine, but happy to take a look at the code if you like

**Comment by pabrams** [comment]
Thanks, and feel free to comment on the code

**Comment by pabrams** [comment]
This functionality was added in #254 , but it was added to the older Bazecor 0.3.3, not Bazecor 1.0, which I didn't know about at the time.  Anyway, it can still be cherry-picked to the Beta version. I don't need it that badly so I didn't do it yet.

**Comment by javierguzman** [comment]
Nowadays you can change the layer name so I close this
