### ISSUE TITLE
Periodic White Screen

### ISSUE THREAD

**Issue by jeffnm** [Dygmalab/Bazecor#25]
**Describe the bug**
Sometimes Bazecor suddenly just has a white screen in the window. This happens on Mac 10.15.2. 

**To Reproduce**
1. Open Bazecor and connect to the keyboard
2. Click on a key and change it (led is fine)
3. Save the configuration
4. Make another change and save the configuration again.
5. If you do this relatively quickly, or a few times, it will suddenly get a white screen inside the window, and the only way to recover seems to be to quit the application and reopen it. The last save may or may not apply.

**Expected behavior**
I'd expect to still be able to use the application.

**Screenshots**
![Screen Shot 2020-01-02 at 10 14 00 AM](https://user-images.githubusercontent.com/651304/71677498-9c378180-2d48-11ea-80c7-de24b82224ea.png)

**Desktop (please complete the following information):**
 - OS: Mac 10.15.2
 - Bazecor Version: 0.1.0

**Additional context**
This white screen looks like same as when Bazecor is first opening.

**Comment by Kawahal** [comment]
I also see the same behaviour whenever I click on any of the "blocked" layers (Layer -1 and Layer -2).

**Comment by algernon** [comment]
This usually happens when there's an uncaught exception in the application. If you open the developer console (`Ctrl+Shift+I` on Win and Linux, `Cmd+Shift+I` on Mac), the console there should have more information.

We're aware of the root cause, and are working on a fix for the next Bazecor release.

(See [Trello#28](https://trello.com/c/f7dHoDmA/28-showing-hardcoded-layers-can-easily-error-out) too).

**Comment by AlexDygma** [comment]
Mac version now is fairly stable, but if more white screen issues a part form the ones mentioned on #82 arise, we will open new issues with more information.
