### ISSUE TITLE
1.0.0b10: Saving the 17th macro deletes all macros!

### ISSUE THREAD

**Issue by massimiliano-della-rovere** [Dygmalab/Bazecor#292]
**Describe the bug**
When I save the 17th macro, all macros are deleted. You won't be aware of what happened, until you change the section of bazecor you are in (e.g. move into the key configuration section and then back to the macro editor)

**To Reproduce**
1. create and the save the 17th macro in the macro editor
2. change the current bazecor page (e.g. go to the keyboard configuration)
3. go back to the macro editor page
4. Only the default "Hey, Dygmates!" remains

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04LTS
 - Bazecor Version: 1.0.0b10

**Comment by AlexDygma** [comment]
Hey @massimiliano-della-rovere !

I have just tried to replicate this issue in the current beta and I cant, are you still having this problem?

**Comment by massimiliano-della-rovere** [comment]
not with b12

Il giorno mer 1 dic 2021 alle ore 10:58 AlexDygma ***@***.***>
ha scritto:

**Comment by AlexDygma** [comment]
Ok, so it was solved on this beta, another bug squashed!

**Comment by SinH4** [comment]
I have exactly the same issue with 1.0.0-beta15, except that for me it happens when saving the 98th macro instead of the 17th, despite Bazecor telling me that the macro memory is only 47.4% full.

Behavior and reproduction is exactly as described in the original bug report, except replace the number 17 with 98.

Bazecor Version: 1.0.0b15
OS: happens on both Debian 11 and an up-to-date Arch Linux system
