### ISSUE TITLE
Missing "context" key

### ISSUE THREAD

**Issue by Mywk** [Dygmalab/Bazecor#33]
On the key config list, the "context" key is unavailable, this can temporarily be fixed by simulating a  Shift+F10 (F10 with shift modifier) but the key should still exist in the list by itself.

The mouse configuration options do not seem to be working either.

Operative System: Windows 10
Bazecor Version: 0.1.0

**Comment by algernon** [comment]
The mouse configurations do not work, because the firmware shipped with the Raise doesn't have the plugin enabled. They will work as soon as new, mouse-supporting firmware is flashed.

As for the context key: try the `App` key in the `Navigation` group. `App` is probably not the best name for the key - but that's how it is called in the USB HID spec, so we went with that. It might make sense to rename it to something else (`Menu` or `Context` come to mind)

@LuisSevilla do you have any input on the naming?

**Comment by LuisSevilla** [comment]
@algernon Just saw this. I think Menu is a better name than App.
