### ISSUE TITLE
Mouse movment keybindings doen't work

### ISSUE THREAD

**Issue by EdvinOlofsson** [Dygmalab/Bazecor#40]
**Describe the bug**
In the Bazecore program you can map keys to mouse movment. N, S, SW, NW, etc...
This doen't work. Using programs such as xev to monitor keyboard/mouse events, I don't see any event registered at all. 

**To Reproduce**
Map the mouse movment to a key and press it.

**Expected behavior**
The mouse to move slightly on the screen

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS
 - Bazecor Version: 0.1.0

**Additional context**

**Comment by algernon** [comment]
This is fixed on master, at least the normal mouse movements (supposedly N, S, SW, NW, etc too). The `MouseKeys` plugin is not enabled in the factory firmware, but will be in the next firmware update (Bazecor master already has the updated firmware), which is why the keys do not work.

At the moment, Bazecor has no way of detecting what plugins are enabled on the firmware-side, so it offers all possible keys for mapping, even if they might be unsupported by the firmware.

**Comment by EdvinOlofsson** [comment]
Perfect! Thanks
