### ISSUE TITLE
Shift Layer doesn't work when "locked" in another layer

### ISSUE THREAD

**Issue by GameOverture** [Dygmalab/Bazecor#44]
Shift layer will only work if I'm in layer '0'. If I lock to layer '2', keys bound in that layer that are supposed to "Shift to Layer 1" will not work.

**Comment by algernon** [comment]
The thing is, layers are stacked in their index order. When you lock to layer 2, then layer 0 and 2 will be active, with layer 2 shadowing layer 0. When you shift to layer 1, then 0, 1, and 2 will be active, with 2 shadowing the other two. So, it "works", but not as you would expect it, I suppose.

Which is why we're working on a way to change how layers work: instead of stacking in index order, they'd stack in activation order. So if you lock to layer 2, and then shift to 1, 1 will be on top. At least, that's the plan, but it will be a while until we get there (it requires substantial firmware-side work).

**Comment by ryanerwin** [comment]
> shift to layer 1, then 0, 1, and 2 will be active, with 2 shadowing the other two. So, it "works", but not as you would expect it

Could you please write in a little bit more detail about how this is supposed to work?
There are two built in layers, layer 0 and layer 1... How does that impact the rest of our configuration? Can we delete 0 and 1? Can we customize them? Each time I try, Bazecor crashes...


I suppose that I need "Layer X" my default QWERTY layout with reduced keys, "Layer Y" should make up for all the keys that the dygma keyboard doesn't have (delete, arrows, tilde, backtick, page up/down/home/end/print screen)...

Should I make the "Layer Y" with these extra keys Layer 2 or Layer 3 or which layer?

Should I use Shift to Layer or Lock to Layer to toggle from Layer X to layer Y? And which to use for returning to Layer X?

Do the LEDs change instantly when using Shift to Layer or only on Lock to Layer?

I'm really interested in Dygma from a productivity perspective...

**Comment by AlexDygma** [comment]
After testing this, with version 0.2.4 is working as intended, the changes have been implemented in the most recent firmware available.
