### ISSUE TITLE
README needs to be updated with Getting Started Section

### ISSUE THREAD

**Issue by yeungh** [Dygmalab/Bazecor#45]
Looking through the issue log it seems people are having trouble getting the application to build, myself included. . Some recommendations is to use NodeJS version 10 instead of the most recent stable version. 

I'd like to have the README.MD updated with the Getting Started section to explain what the development environment should look like in order to properly build the application to debug. It would also be nice to have a Contributing section just so we know what branching/merging strategy we should use or are we just pushing all features directly to the development branch?

**Comment by hirisov** [comment]
This would be great, I would like to add support for a new layout, but Bazecor does not compile with the current nodejs version, then I accidentally find this thread and successfully compile it with version 10,  but it gives an empty canvas after start and some not very descriptive electronjs errors :( Some "official" info would be great for how to set up for development and how to contribute.

**Comment by GazHank** [comment]
Hi @yeungh & @hirisov 

sorry it's taken a while to respond, I certainly recognise your pain, I had so much trouble initially getting everything working.  Even when I did get it all working, I couldn't really share instructions as so much trial and error meant I want sure which steps were really needed.

I'll give it a try to describe all of the steps needed to get a fully functional environment to build Bazecor.  I've just installed a fresh OS on a blank SSD, so I can hopefully confirm all of the steps needed, do please let me know if anything could be clarified or simplified.

While my install was conducted on Linux (Ubuntu 20.04.2 LTS), I'm far more familiar with Windows, so I'll try to help on other platforms if I can.  

The main steps are:
1. Install Node.js
2. Install build tools
3. Clone the Bazecor Repository
4. Have Yarn download (and rebuild) the required packages 
5. Enjoy! (Build or Test Bazecor)

## 1. Install Node.js
You can find instructions at https://nodejs.org/ or https://nodejs.org/en/download/package-manager/

I'd suggest using the current release (v16 at the moment) , or you could try the LTS (v14) if you prefer, but be very careful if you try to use older versions as you may hit compatibility issues
## 2. Install Build tools
There are a few tools you need to build Bazecor and the things it depends upon:
- Git - Since you are viewing this on Github you probably know why git is useful :-)
- Yarn - all of the packaging and building of Bazecor is handled by yarn
- Build essentials (support for C, Python etc) - This is mainly needed to build/rebuild native dependencies - There is a chance that we can remove this dependency in the future, but this is all good stuff to have on your machine if you are developing stuff

### Git
https://git-scm.com/downloads

### Yarn
https://classic.yarnpkg.com/

### Build Essentials
**Windows:** 
1.  run `npm install --global windows-build-tools`

**Linux:**
1. run `sudo apt-get install -y build-essential`
2. run `sudo apt-get install libudev-dev`

**Mac:** 
1. _< not sure, perhaps someone with a fruit machine can confirm? >_

## 3. Clone the Bazecor Repository

1. Open a command prompt (whatever your poison: bash, cmd, powershell)
2. Make (/navigate to) a directory to keep you git repositories in
3. run `git clone https://github.com/Dygmalab/Bazecor.git`

## 4. Have Yarn download the required packages

1. run `yarn`

While this will probably result in lots of warning about some packages which we depend upon being out of date, this should build successfully.

Your can also run `yarn rebuild` if you want to need to recompile any of the native packages, but we have configured yarn so that it should do this by default.

## 5. Enjoy! (Build or Test Bazecor)
Now is the time to have some fun (hopefully!)

You should now be ready to start testing or building Bazecor!

To test things run `Yarn start`, this will run the app in a dev environment which is great for testing when you have made a code tweak and what to check if it is working.

To build a packaged executable run `yarn build:osx` / `build:win` / `build:linux`
While you could run `build:all`, most environments can't cross compile, so it's probably best to just build for your local machine.

-----

So from a fresh Ubuntu 20.04.2 LTS install (standard install)

```
sudo snap install curl
curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
sudo apt-get install -y nodejs

sudo apt install git
sudo npm install yarn
sudo apt-get install -y build-essential
sudo apt-get install libudev-dev

mkdir Git
cd Git
git clone https://github.com/Dygmalab/Bazecor.git
cd Bazecor

yarn

yarn start
```

-----

Please do let me know if this is helpful, or if you face any issues with any of the steps, There might be some extra tweaks needed on Windows or Mac especially, but if this is useful then I'd like to update the instructions based on your feedback if possible.

@AlexDygma would you be able to take a review too, or have other members of the team take a look, especially anyone with experience on the Mac side, I think it would be great if we can make it easier for others to build and interact with the code, and hopefully help make Bazecor even better :-)

Cheers

Gaz

**Comment by martinhauke** [comment]
It's probably a good idea to add a `.nvmrc` file and run `nvm use && yarn`.

**Comment by javierguzman** [comment]
Bazecor is like any other Nodejs project. You just need node and yarn(we do not use npm). Installing these two things will take care of the build stuff you need. If you are still having problems with this, feel free to reopen and specify exactly what errors/problems you are facing.
