### ISSUE TITLE
On Screen Keyboard Overlay for Defy

### ISSUE THREAD

**Issue by IronMania** [Dygmalab/Bazecor#456]
**Is your feature request related to a problem? Please describe.**
I want to write characters which I seldom use. I do not know where to find them on the many layers.

**Describe the solution you'd like**
I would like to enable an Onscreen Overlay where I can see the current keys for the layout. When I hit switch I see all the capslock characters and when i enable an other layer I would like to see all the keys on the layer.

**Describe alternatives you've considered**
For my current old qwertz keyboard I used RENEO to remap my hotkeys:  https://github.com/Rojetto/ReNeo/blob/v1.5.4/README_EN.md
Here I can enable and disable the layout really nice for learning a new layout. The Problem is that the layout there is not for the Defy.

**Additional context**
maybe there does a tool like that exist where you can export the layout from Bazecore and import it into the other tool.

**Comment by javierguzman** [comment]
Hello @IronMania! I am going to close this because it is duplicated. Having an overlay showing the current layer is something already under our radar, so sooner or later will make it. On the other hand I am not sure the Bazecor configuration can be reused by another tool as the Bazecor configuration is customized for Dygma products, if that makes sense for you.

Feel free to reopen if I have misunderstood you.

Regards

**Comment by IronMania** [comment]
@javierguzman just one question, can I track that backlog item somewhere? I would like to know if I need to finde a replacement for that feature or if it comes the next weeks.
