### ISSUE TITLE
Bazecor 0.2: Changing LED intensity does not persist when moving to another machine 

### ISSUE THREAD

**Issue by mortenlerudjordet** [Dygmalab/Bazecor#47]
**Describe the bug**
On FW 0.2 and Bazecor 0.2 Windows 10.
Saving LED intensity to something else than 100% will work on the machine where Bazecor is installed. Though moving the keyboard to another machine will reset the led intensity to 100%

Moving back to the machine with Bazecor installed the LED intensity is still 100%

**To Reproduce**
1. Drag led intensity to something else than 100%
2. Save to keyboard
3. Check that LED intensity is diminished 
4. Unplug keyboard
5. Plug in keyboard into another Windows machine without Bazecor installed
6. LED intensity is back to 100%

**Expected behavior**
Retained saved LED intensity even when switching machine keyboard is connected to.

**Desktop (please complete the following information):**
 - OS: Win10 (latest)
 - Bazecor Version: 0.2
- FW Version: 0.2

**Comment by AlexDygma** [comment]
Ok so after looking into this, i found that this setting: `led.brightness` that was configurable via [Focus API](https://github.com/Dygmalab/Bazecor/blob/development/FOCUS_API.md) was not persisted in the eeprom because basically the whole handler was missing, so in the next bazecor milestone 0.2.5  this fix will be included.

**Comment by AlexDygma** [comment]
The fix is introduced in the latest firmware attached to the pull request to solve this bug.
