### ISSUE TITLE
Restore backup does not restore names, macros and superkeys

### ISSUE THREAD

**Issue by GCCoding314** [Dygmalab/Bazecor#524]
**Describe the bug**
I have a backup file which contains non-default layer names and custom macros. When I restore this file, the layer names change temporarily in the bazecor interface, but after saving a new change, the layer names display the previous default names e.g. "L2". Looking in the newly created backup shows that the previous names and macros (none) are saved in the new json file instead of the restored backup settings.

**Expected behavior**
I expect after restoring a backup, settings such as layer names and previously created macros/superkeys are loaded into the current keyboard configuration, ready for continuing edits/immediate use.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Bazecor Version: v1.3.4

**Additional context**
The superkeys editor is currently blanked out and I cannot create or edit superkeys as of now.  The initial backup was initially generated from a virtual Defy, in anticipation of receiving the physical defy which I now have.

**Comment by alexpargon** [comment]
Hello, @GCCoding314 !!

You are right, that was taken out due to it affecting some users, as a final solution, we will show a backup data selector to allow you to decide what gets restored and what not.

but it's still pending! when we add that feature we will close this issue :) (it should not take long)
