### ISSUE TITLE
Shift to Layer does not work depending on the current and target layer.

### ISSUE THREAD

**Issue by gautamjain** [Dygmalab/Bazecor#55]
**Describe the bug**
"Shift to Layer" does not work if the target layer # is less than the current layer #.    For example - if you are currently on Layer 4 and you press 'Shift to 3', nothing happens.  However, if you press 'Shift to 5', it works as expected.

**Desktop:**
 - OS: Windows 10
 - Bazecor Version: 0.2.0

**Comment by alexvy86** [comment]
I'd imagine this is probably by design right now, but could be changed.

I can see layers being implemented as a single stack, and each keypress goes down that stack looking for the current layer (which should be the first active layer encountered). If the pressed key does something in that layer, then do it, and if it's transparent, keep going down the stack until you find a non-transparent key, and do what it says). In this approach, shift-to-layer probably makes the "target layer" active, but it does not deactivate the current layer. So if the target layer is below the current one, all keys keep doing what they do in the current layer.

Transparent keys and how they work are probably one of the main concerns with shift-to-layer. My intuition would be that if I'm on layer 4 and shift to 3, any transparent keys on layer 3 do what the corresponding key in layer 4 says. But if the layers are implemented as a single stack, I can see how this becomes problematic, and transparent keys in layer 3 could end up doing what they do in layer 2. If this is how this currently works, I would ask myself if the shift-to-layer functionality should be thinking in terms of a single stack of layers, or purely as taking the target layer and making a "virtual copy" of that layer above the current one.

**Comment by AlexDygma** [comment]
This was fixed as per Bazecor 0.2.3 Firmware Update, now the keyboard is capable of shifting to any layer form any layer.
