### ISSUE TITLE
Dygma devices firmware customization, where to start?

### ISSUE THREAD

**Issue by sfavazza** [Dygmalab/Bazecor#848]
I would like to customize the firmware for my Dygma Defy, but I am having difficulty to find the right repository(ies). So far I identified few Defy related once but there is not enough documentation to understand how they work together and whether they all concur to create the binary files released [here](https://github.com/Dygmalab/Firmware-release/tree/main).

Is any (or all) of the following required to customize a Dygma Defy keyboard firmware?
- [KaleidoscopePuglinLedLibraryDefy](https://github.com/Dygmalab/KaleidoscopePuglinLedLibraryDefy)
- [DefyCommunications](https://github.com/Dygmalab/DefyCommunications)
- [Kaleidoscope-Bundle-Dygma](https://github.com/Dygmalab/Kaleidoscope-Bundle-Dygma) (although the README clearly states that this is related to the Dygma Raise)

Pretty sure I am missing something here...

**Comment by alexpargon** [comment]
Hey there @sfavazza ! I will pin this question as it's good for everyone to know the right path to follow when trying to modify the FW.

### **Dygma Raise**
- https://github.com/Dygmalab/raise-firmware <- This is the main repository, just follow the instructions, but bear in mind that this repo relates to the beta version of the FW (1.0.X-beta) in its `master `branch.
- then install https://github.com/dygmalab/kaleidoscope-bundle-dygma as per instructions in the repo above.
- https://github.com/Dygmalab/KaleidoscopeTest <- In case you want to work with the stable version of the Raise, the updated Kaleidoscope repository for the stable branch (0.3.8) is here, change the branch of the `raise-firmware` repo to `stableRelease` to make it compile as expected, then create a folder called `updatedDygma` on the same folder as the `kaleidoscope-bundle-dygma` folder is in, so that the makefile finds the compilation resources.

### **Dygma Defy Wired**
- https://github.com/Dygmalab/NeuronWired <- This is the repository for the neuron wired firmware, it's lacking a readme right now 👀, will be fixed soon, you just need that repository, everything needed is imported as a submodule of that repo, just install the RP2040 SDK in your path -> https://www.raspberrypi.com/documentation/microcontrollers/c_sdk.html

### **Dygma Defy Wireless**
- https://github.com/Dygmalab/NeuronWireless/ <- This is the repo for the wireless version of the neuron, you can follow the instructions provided to start working with it, the Nordic SDK will have to be downloaded by yourself like explained in the readme.

### **Dygma Raise 2**
- https://github.com/Dygmalab/NeuronWireless_raise2/ <- This is the repo for the Raise 2 neuron, you can follow the instructions provided to start working with it, the Nordic SDK will have to be downloaded by yourself like explained in the readme file, just follow the instructions :).

if you need any other explanation ask it here so that other devs can benefit from it!

**Comment by sfavazza** [comment]
Hi again, I am creating a containerized environment to build the [neuron-wired project](https://github.com/sfavazza/NeuronWired/tree/parse-pressed-when-pressing-other-keys).

If a change to the firmware would be accepted how would it propagate to the other keyboard configurations? 
In other words, which is the intended target sub-repo one would work on to make sure a change is inherited across Dygma keyboard? 
Do you have a resource explaining the rolling out of a new feature?

Do you maybe have an example of a community contribution? Just to have an hint of what is the process.

**Comment by alexpargon** [comment]
> Hi again, I am creating a containerized environment to build the [neuron-wired project](https://github.com/sfavazza/NeuronWired/tree/parse-pressed-when-pressing-other-keys).
> 
> If a change to the firmware would be accepted how would it propagate to the other keyboard configurations? In other words, which is the intended target sub-repo one would work on to make sure a change is inherited across Dygma keyboard? Do you have a resource explaining the rolling out of a new feature?
> 
> Do you maybe have an example of a community contribution? Just to have an hint of what is the process.

Hey there! 

Just updated my previous comment with the link for the Raise2 repo and saw your comment, as soon as I can I will update you on this!

**Comment by sboesebeck** [comment]
hmm... i was also trying  to get that to work, but the neuron wireless (which seems to be a bit outdated) does not compile on my machines - tried it with several fresh installes. Is there some kind of howto anywhere?
